#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Politique de confidentialite, dans les dix-huit langues.

Cette page vit hors de l'application : elle s'ouvre dans un onglet a part
depuis les Reglages, et elle etait restee en francais partout. Un lecteur
japonais ne pouvait pas lire ce qu'il acceptait — c'est le seul texte de
l'application dont on ne peut pas dire « il verra bien ».

Le texte est celui de la page francaise, traduit ; rien n'y est ajoute ni
retire. Les noms de service (api.quran.com, OpenStreetMap, Google Play) et
le terme technique localStorage restent tels quels dans toutes les langues.
"""

LOTS = {

"priv.lang": {
 "fr": "Langue", "en": "Language", "es": "Idioma", "ru": "Язык",
 "bs": "Jezik", "ar": "اللغة", "tr": "Dil", "fa": "زبان",
 "ur": "زبان", "hi": "भाषा", "bn": "ভাষা", "id": "Bahasa",
 "ms": "Bahasa", "zh": "语言", "ja": "言語", "so": "Luqadda",
 "sw": "Lugha", "ha": "Harshe",
},

"priv.title": {
 "fr": "Politique de confidentialité — Sakina",
 "en": "Privacy Policy — Sakina",
 "es": "Política de privacidad — Sakina",
 "ru": "Политика конфиденциальности — Sakina",
 "bs": "Politika privatnosti — Sakina",
 "ar": "سياسة الخصوصية — Sakina",
 "tr": "Gizlilik Politikası — Sakina",
 "fa": "سیاست حریم خصوصی — Sakina",
 "ur": "رازداری کی پالیسی — Sakina",
 "hi": "गोपनीयता नीति — Sakina",
 "bn": "গোপনীয়তা নীতি — Sakina",
 "id": "Kebijakan Privasi — Sakina",
 "ms": "Dasar Privasi — Sakina",
 "zh": "隐私政策 — Sakina",
 "ja": "プライバシーポリシー — Sakina",
 "so": "Siyaasadda Sirta — Sakina",
 "sw": "Sera ya Faragha — Sakina",
 "ha": "Manufar Sirri — Sakina",
},

"priv.updated": {
 "fr": "Dernière mise à jour : 2026",
 "en": "Last updated: 2026",
 "es": "Última actualización: 2026",
 "ru": "Последнее обновление: 2026",
 "bs": "Posljednja izmjena: 2026.",
 "ar": "آخر تحديث: 2026",
 "tr": "Son güncelleme: 2026",
 "fa": "آخرین به‌روزرسانی: ۲۰۲۶",
 "ur": "آخری تازہ کاری: 2026",
 "hi": "अंतिम अद्यतन: 2026",
 "bn": "সর্বশেষ হালনাগাদ: ২০২৬",
 "id": "Pembaruan terakhir: 2026",
 "ms": "Kemas kini terakhir: 2026",
 "zh": "最后更新：2026 年",
 "ja": "最終更新：2026年",
 "so": "Cusboonaysiintii ugu dambeysay: 2026",
 "sw": "Sasisho la mwisho: 2026",
 "ha": "Sabuntawa ta ƙarshe: 2026",
},

"priv.sum.h": {
 "fr": "En résumé", "en": "In short", "es": "En resumen", "ru": "Коротко",
 "bs": "Ukratko", "ar": "باختصار", "tr": "Özetle", "fa": "به‌اختصار",
 "ur": "خلاصہ", "hi": "संक्षेप में", "bn": "সংক্ষেপে", "id": "Ringkasnya",
 "ms": "Ringkasnya", "zh": "简而言之", "ja": "要点", "so": "Kooban",
 "sw": "Kwa kifupi", "ha": "A taƙaice",
},

"priv.sum.b1": {
 "fr": "Aucun compte requis", "en": "No account required",
 "es": "Sin cuenta", "ru": "Без учётной записи", "bs": "Bez računa",
 "ar": "لا حاجة إلى حساب", "tr": "Hesap gerekmez", "fa": "بدون نیاز به حساب",
 "ur": "کوئی اکاؤنٹ درکار نہیں", "hi": "कोई खाता नहीं चाहिए",
 "bn": "কোনো অ্যাকাউন্ট লাগে না", "id": "Tanpa akun", "ms": "Tanpa akaun",
 "zh": "无需账户", "ja": "アカウント不要", "so": "Xisaab looma baahna",
 "sw": "Hakuna akaunti inayohitajika", "ha": "Ba a buƙatar asusu",
},

"priv.sum.b2": {
 "fr": "Aucune publicité", "en": "No ads", "es": "Sin publicidad",
 "ru": "Без рекламы", "bs": "Bez reklama", "ar": "لا إعلانات",
 "tr": "Reklam yok", "fa": "بدون تبلیغات", "ur": "کوئی اشتہار نہیں",
 "hi": "कोई विज्ञापन नहीं", "bn": "কোনো বিজ্ঞাপন নেই", "id": "Tanpa iklan",
 "ms": "Tanpa iklan", "zh": "无广告", "ja": "広告なし", "so": "Xayaysiin ma jirto",
 "sw": "Hakuna matangazo", "ha": "Babu talla",
},

"priv.sum.b3": {
 "fr": "Aucun tracking", "en": "No tracking", "es": "Sin rastreo",
 "ru": "Без слежки", "bs": "Bez praćenja", "ar": "لا تتبّع",
 "tr": "Takip yok", "fa": "بدون ردیابی", "ur": "کوئی ٹریکنگ نہیں",
 "hi": "कोई ट्रैकिंग नहीं", "bn": "কোনো ট্র্যাকিং নেই", "id": "Tanpa pelacakan",
 "ms": "Tanpa penjejakan", "zh": "无追踪", "ja": "追跡なし", "so": "Raad-raac ma jirto",
 "sw": "Hakuna ufuatiliaji", "ha": "Babu bin diddigi",
},

"priv.sum.b4": {
 "fr": "Aucune revente de données", "en": "No data selling",
 "es": "Sin venta de datos", "ru": "Данные не продаются",
 "bs": "Podaci se ne prodaju", "ar": "لا بيع للبيانات",
 "tr": "Veri satışı yok", "fa": "بدون فروش داده",
 "ur": "ڈیٹا کی فروخت نہیں", "hi": "डेटा की बिक्री नहीं",
 "bn": "তথ্য বিক্রি নেই", "id": "Tanpa penjualan data",
 "ms": "Tanpa penjualan data", "zh": "不出售数据", "ja": "データの販売なし",
 "so": "Xogta lama iibiyo", "sw": "Hakuna kuuza data", "ha": "Ba a sayar da bayanai",
},
"priv.sum.p": {
 "fr": "Sakina fonctionne <strong>sans serveur propre</strong> : toutes vos données restent sur votre appareil. L'application n'a pas de compte, ne vous demande jamais votre identité, et ne contient aucun traceur publicitaire ou analytique.",
 "en": "Sakina runs <strong>without a server of its own</strong>: all your data stays on your device. The app has no accounts, never asks who you are, and contains no advertising or analytics trackers.",
 "es": "Sakina funciona <strong>sin servidor propio</strong>: todos sus datos permanecen en su dispositivo. La aplicación no tiene cuentas, nunca le pide su identidad y no contiene ningún rastreador publicitario o analítico.",
 "ru": "Sakina работает <strong>без собственного сервера</strong>: все ваши данные остаются на устройстве. В приложении нет учётных записей, оно никогда не спрашивает, кто вы, и не содержит рекламных или аналитических трекеров.",
 "bs": "Sakina radi <strong>bez vlastitog servera</strong>: svi vaši podaci ostaju na uređaju. Aplikacija nema račune, nikada ne pita ko ste i ne sadrži nikakve reklamne ni analitičke pratioce.",
 "ar": "يعمل تطبيق Sakina <strong>دون خادم خاص به</strong>: تبقى كل بياناتك على جهازك. لا حسابات في التطبيق، ولا يسألك يوماً عن هويتك، ولا يحوي أي أداة تتبّع إعلانية أو تحليلية.",
 "tr": "Sakina <strong>kendine ait bir sunucu olmadan</strong> çalışır: tüm verileriniz cihazınızda kalır. Uygulamada hesap yoktur, kim olduğunuz hiç sorulmaz ve hiçbir reklam veya analiz izleyicisi bulunmaz.",
 "fa": "Sakina <strong>بدون سرور اختصاصی</strong> کار می‌کند: همهٔ داده‌های شما روی دستگاه خودتان می‌ماند. برنامه حساب کاربری ندارد، هرگز هویت شما را نمی‌پرسد و هیچ ردیاب تبلیغاتی یا تحلیلی ندارد.",
 "ur": "Sakina <strong>اپنے سرور کے بغیر</strong> چلتا ہے: آپ کا سارا ڈیٹا آپ ہی کے آلے پر رہتا ہے۔ ایپ میں کوئی اکاؤنٹ نہیں، یہ کبھی آپ کی شناخت نہیں پوچھتی، اور اس میں کوئی اشتہاری یا تجزیاتی ٹریکر نہیں۔",
 "hi": "Sakina <strong>अपने किसी सर्वर के बिना</strong> चलता है: आपका सारा डेटा आपके ही उपकरण पर रहता है। ऐप में कोई खाता नहीं है, यह कभी आपकी पहचान नहीं पूछता, और इसमें कोई विज्ञापन या विश्लेषण ट्रैकर नहीं है।",
 "bn": "Sakina <strong>নিজস্ব সার্ভার ছাড়াই</strong> চলে: আপনার সমস্ত তথ্য আপনার যন্ত্রেই থাকে। অ্যাপে কোনো অ্যাকাউন্ট নেই, এটি কখনো আপনার পরিচয় জানতে চায় না, এবং এতে কোনো বিজ্ঞাপনী বা বিশ্লেষণী ট্র্যাকার নেই।",
 "id": "Sakina berjalan <strong>tanpa server sendiri</strong>: semua data Anda tetap di perangkat Anda. Aplikasi ini tidak punya akun, tidak pernah menanyakan identitas Anda, dan tidak memuat pelacak iklan maupun analitik.",
 "ms": "Sakina berjalan <strong>tanpa pelayan sendiri</strong>: semua data anda kekal pada peranti anda. Aplikasi ini tiada akaun, tidak pernah bertanya identiti anda, dan tiada penjejak iklan mahupun analitik.",
 "zh": "Sakina <strong>没有自己的服务器</strong>：您的全部数据都留在设备上。应用没有账户，从不询问您的身份，也不含任何广告或分析追踪器。",
 "ja": "Sakina は<strong>自前のサーバーを持たずに</strong>動作します。あなたのデータはすべて端末内に留まります。アカウントはなく、身元を尋ねることもなく、広告や解析のトラッカーも一切含みません。",
 "so": "Sakina waxay u shaqaysaa <strong>iyada oo aan lahayn server u gaar ah</strong>: dhammaan xogtaadu waxay ku hartaa qalabkaaga. Barnaamijku xisaab ma leh, weligiis kuma weydiiyo aqoonsigaaga, mana wato wax raad-raac xayaysiineed ama falanqayneed ah.",
 "sw": "Sakina hufanya kazi <strong>bila seva yake mwenyewe</strong>: data yako yote hubaki kwenye kifaa chako. Programu haina akaunti, haikuulizi kamwe wewe ni nani, na haina kifuatiliaji chochote cha matangazo au uchanganuzi.",
 "ha": "Sakina tana aiki <strong>ba tare da sabar ta ba</strong>: duk bayananka suna zama a na'urarka. Manhajar ba ta da asusu, ba ta taɓa tambayar ko wane ne kai ba, kuma ba ta ɗauke da wani mai bin diddigin talla ko na bincike ba.",
},

"priv.dev.h": {
 "fr": "Données stockées sur votre appareil",
 "en": "Data stored on your device",
 "es": "Datos guardados en su dispositivo",
 "ru": "Данные, хранящиеся на устройстве",
 "bs": "Podaci pohranjeni na vašem uređaju",
 "ar": "البيانات المخزَّنة على جهازك",
 "tr": "Cihazınızda saklanan veriler",
 "fa": "داده‌های ذخیره‌شده روی دستگاه شما",
 "ur": "آپ کے آلے پر محفوظ ڈیٹا",
 "hi": "आपके उपकरण पर संग्रहीत डेटा",
 "bn": "আপনার যন্ত্রে সংরক্ষিত তথ্য",
 "id": "Data yang disimpan di perangkat Anda",
 "ms": "Data yang disimpan pada peranti anda",
 "zh": "存储在您设备上的数据",
 "ja": "端末に保存されるデータ",
 "so": "Xogta lagu keydiyo qalabkaaga",
 "sw": "Data iliyohifadhiwa kwenye kifaa chako",
 "ha": "Bayanan da ake ajiyewa a na'urarka",
},

"priv.dev.p1": {
 "fr": "Sakina enregistre localement (<code>localStorage</code>, jamais transmis à un serveur) :",
 "en": "Sakina saves locally (<code>localStorage</code>, never sent to a server):",
 "es": "Sakina guarda localmente (<code>localStorage</code>, nunca enviado a un servidor):",
 "ru": "Sakina сохраняет локально (<code>localStorage</code>, никогда не отправляется на сервер):",
 "bs": "Sakina pohranjuje lokalno (<code>localStorage</code>, nikad ne šalje na server):",
 "ar": "يحفظ Sakina محلياً (<code>localStorage</code>، ولا يُرسل إلى أي خادم):",
 "tr": "Sakina yerel olarak kaydeder (<code>localStorage</code>, hiçbir sunucuya gönderilmez):",
 "fa": "Sakina به‌صورت محلی ذخیره می‌کند (<code>localStorage</code>، هرگز به سروری فرستاده نمی‌شود):",
 "ur": "Sakina مقامی طور پر محفوظ کرتا ہے (<code>localStorage</code>، کبھی کسی سرور کو نہیں بھیجا جاتا):",
 "hi": "Sakina स्थानीय रूप से सहेजता है (<code>localStorage</code>, कभी किसी सर्वर को नहीं भेजा जाता):",
 "bn": "Sakina স্থানীয়ভাবে সংরক্ষণ করে (<code>localStorage</code>, কখনো কোনো সার্ভারে পাঠানো হয় না):",
 "id": "Sakina menyimpan secara lokal (<code>localStorage</code>, tidak pernah dikirim ke server):",
 "ms": "Sakina menyimpan secara setempat (<code>localStorage</code>, tidak pernah dihantar ke pelayan):",
 "zh": "Sakina 在本地保存（<code>localStorage</code>，绝不发送至服务器）：",
 "ja": "Sakina は端末内に保存します（<code>localStorage</code>。サーバーへは一切送信しません）：",
 "so": "Sakina waxay ku keydisaa qalabkaaga (<code>localStorage</code>, weligeed server looma diro):",
 "sw": "Sakina huhifadhi ndani ya kifaa (<code>localStorage</code>, hakitumwi kamwe kwa seva):",
 "ha": "Sakina tana ajiyewa a cikin na'urar (<code>localStorage</code>, ba a taɓa aika wa sabar ba):",
},
"priv.dev.l1": {
 "fr": "Votre compteur de dhikr, historique de sessions, dhikrs personnalisés",
 "en": "Your dhikr counter, session history and custom dhikrs",
 "es": "Su contador de dhikr, historial de sesiones y dhikrs personalizados",
 "ru": "Ваш счётчик зикра, история сессий и свои зикры",
 "bs": "Vaš brojač zikra, historija sesija i vlastiti zikrovi",
 "ar": "عدّاد الذكر، وسجل الجلسات، والأذكار المخصَّصة",
 "tr": "Zikir sayacınız, oturum geçmişiniz ve kendi zikirleriniz",
 "fa": "شمارگر ذکر، تاریخچهٔ نشست‌ها و ذکرهای شخصی شما",
 "ur": "آپ کا ذکر شمار، نشستوں کی تاریخ اور ذاتی اذکار",
 "hi": "आपका ज़िक्र काउंटर, सत्रों का इतिहास और अपने ज़िक्र",
 "bn": "আপনার জিকির গণক, সেশনের ইতিহাস ও নিজের জিকির",
 "id": "Penghitung zikir, riwayat sesi, dan zikir buatan Anda",
 "ms": "Pembilang zikir, sejarah sesi, dan zikir tersuai anda",
 "zh": "您的赞念计数、会话历史与自定赞念",
 "ja": "ズィクルのカウンター、セッション履歴、自作のズィクル",
 "so": "Tirinta dhikrigaaga, taariikhda fadhiyada iyo dhikriyada aad samaysatay",
 "sw": "Kihesabu chako cha dhikri, historia ya vipindi na dhikri zako mwenyewe",
 "ha": "Ma'aunin zikirinka, tarihin zamanka da zikirai naka",
},

"priv.dev.l2": {
 "fr": "Vos préférences (thème, couleur, sons, format d'heure)",
 "en": "Your preferences (theme, colour, sounds, time format)",
 "es": "Sus preferencias (tema, color, sonidos, formato horario)",
 "ru": "Ваши настройки (тема, цвет, звуки, формат времени)",
 "bs": "Vaše postavke (tema, boja, zvukovi, format vremena)",
 "ar": "تفضيلاتك (السمة، اللون، الأصوات، صيغة الوقت)",
 "tr": "Tercihleriniz (tema, renk, sesler, saat biçimi)",
 "fa": "ترجیحات شما (پوسته، رنگ، صداها، قالب زمان)",
 "ur": "آپ کی ترجیحات (تھیم، رنگ، آوازیں، وقت کی شکل)",
 "hi": "आपकी प्राथमिकताएँ (थीम, रंग, ध्वनियाँ, समय प्रारूप)",
 "bn": "আপনার পছন্দ (থিম, রঙ, শব্দ, সময়ের বিন্যাস)",
 "id": "Preferensi Anda (tema, warna, suara, format waktu)",
 "ms": "Keutamaan anda (tema, warna, bunyi, format masa)",
 "zh": "您的偏好（主题、颜色、声音、时间格式）",
 "ja": "設定（テーマ、色、サウンド、時刻表示形式）",
 "so": "Doorbidyadaada (mawduuca, midabka, codadka, qaabka waqtiga)",
 "sw": "Mapendeleo yako (mandhari, rangi, sauti, muundo wa saa)",
 "ha": "Zaɓinka (jigo, launi, sautuka, tsarin lokaci)",
},

"priv.dev.l3": {
 "fr": "Votre position géographique <strong>si vous l'autorisez</strong> (voir ci-dessous), pour calculer les horaires de prière et la direction de la Qibla",
 "en": "Your location <strong>if you allow it</strong> (see below), to compute prayer times and the Qibla direction",
 "es": "Su ubicación <strong>si la autoriza</strong> (véase abajo), para calcular los horarios de oración y la dirección de la Qibla",
 "ru": "Ваше местоположение, <strong>если вы разрешите</strong> (см. ниже), для расчёта времени молитв и направления кыблы",
 "bs": "Vašu lokaciju <strong>ako je dopustite</strong> (vidi niže), radi računanja namaskih vremena i smjera kible",
 "ar": "موقعك الجغرافي <strong>إن أذنت بذلك</strong> (انظر أدناه)، لحساب مواقيت الصلاة واتجاه القبلة",
 "tr": "<strong>İzin verirseniz</strong> konumunuz (aşağıya bakın), namaz vakitlerini ve kıble yönünü hesaplamak için",
 "fa": "موقعیت مکانی شما <strong>در صورت اجازه</strong> (پایین‌تر ببینید)، برای محاسبهٔ اوقات نماز و جهت قبله",
 "ur": "آپ کا مقامِ وقوع <strong>اگر آپ اجازت دیں</strong> (نیچے دیکھیں)، نماز کے اوقات اور سمتِ قبلہ نکالنے کے لیے",
 "hi": "आपका स्थान <strong>यदि आप अनुमति दें</strong> (नीचे देखें), नमाज़ के समय और क़िबला की दिशा निकालने के लिए",
 "bn": "আপনার অবস্থান <strong>যদি আপনি অনুমতি দেন</strong> (নিচে দেখুন), নামাজের সময় ও কিবলার দিক নির্ণয়ের জন্য",
 "id": "Lokasi Anda <strong>jika Anda mengizinkan</strong> (lihat di bawah), untuk menghitung waktu salat dan arah kiblat",
 "ms": "Lokasi anda <strong>jika anda benarkan</strong> (lihat di bawah), untuk mengira waktu solat dan arah kiblat",
 "zh": "您的位置（<strong>若您允许</strong>，见下文），用于计算礼拜时间与朝向",
 "ja": "<strong>許可した場合の</strong>位置情報（下記参照）。礼拝時刻とキブラの方角の算出に使います",
 "so": "Goobtaada <strong>haddii aad ogolaato</strong> (eeg hoos), si loo xisaabiyo waqtiyada salaadda iyo jihada qiblada",
 "sw": "Mahali ulipo <strong>ukikubali</strong> (tazama hapa chini), ili kukokotoa nyakati za sala na mwelekeo wa Kibla",
 "ha": "Wurin da kake <strong>idan ka bayar da izini</strong> (duba ƙasa), don ƙididdige lokutan sallah da alkiblar",
},

"priv.dev.l4": {
 "fr": "Votre suivi Qadâ' (prières à rattraper), vos favoris et notes sur les versets du Coran",
 "en": "Your Qada' tracker (missed prayers), your bookmarks and notes on Qur'an verses",
 "es": "Su seguimiento Qadá' (oraciones pendientes), sus favoritos y notas sobre los versículos del Corán",
 "ru": "Ваш учёт када' (пропущенных молитв), закладки и заметки к аятам Корана",
 "bs": "Vaše praćenje kada' (propuštenih namaza), oznake i bilješke uz kur'anske ajete",
 "ar": "متابعة القضاء (الصلوات الفائتة)، ومفضّلاتك وملاحظاتك على آيات القرآن",
 "tr": "Kaza takibiniz (kaçırılan namazlar), Kur'an ayetlerine dair yer imleri ve notlarınız",
 "fa": "پیگیری قضای شما (نمازهای فوت‌شده)، نشان‌شده‌ها و یادداشت‌هایتان بر آیات قرآن",
 "ur": "آپ کا قضا حساب (چھوٹی ہوئی نمازیں)، قرآنی آیات پر پسندیدگیاں اور نوٹس",
 "hi": "आपका क़ज़ा हिसाब (छूटी नमाज़ें), क़ुरआन की आयतों पर पसंद और टिप्पणियाँ",
 "bn": "আপনার কাজা হিসাব (ছুটে যাওয়া নামাজ), কুরআনের আয়াতে পছন্দ ও নোট",
 "id": "Catatan qada Anda (salat yang terlewat), markah dan catatan pada ayat Al-Qur'an",
 "ms": "Rekod qada anda (solat yang tertinggal), penanda dan nota pada ayat al-Quran",
 "zh": "您的补拜记录（欠缺的礼拜）、古兰经节的收藏与笔记",
 "ja": "カダーの記録（未履行の礼拝）、クルアーン章句のブックマークとメモ",
 "so": "Diiwaanka qadada (salaadaha kaa dhaafay), calaamadahaaga iyo qoraaladaada aayadaha Quraanka",
 "sw": "Rekodi yako ya qadaa (sala zilizokosa), alamisho na madokezo kwenye aya za Qur'ani",
 "ha": "Bayanan qada'inka (sallolin da suka kubce), alamominka da bayananka a kan ayoyin Alqur'ani",
},
"priv.dev.p2": {
 "fr": "Ces données restent sur votre téléphone. Désinstaller l'application ou vider les données du navigateur les efface définitivement. Un export JSON manuel est disponible dans <em>Réglages → Exporter mes données</em>.",
 "en": "This data stays on your phone. Uninstalling the app or clearing your browser data erases it for good. A manual JSON export is available under <em>Settings → Export my data</em>.",
 "es": "Estos datos permanecen en su teléfono. Desinstalar la aplicación o borrar los datos del navegador los elimina definitivamente. Hay una exportación JSON manual en <em>Ajustes → Exportar mis datos</em>.",
 "ru": "Эти данные остаются на вашем телефоне. Удаление приложения или очистка данных браузера стирает их окончательно. Ручной экспорт в JSON доступен в <em>Настройках → Экспорт моих данных</em>.",
 "bs": "Ovi podaci ostaju na vašem telefonu. Deinstalacija aplikacije ili brisanje podataka preglednika briše ih trajno. Ručni JSON izvoz nalazi se u <em>Postavke → Izvezi moje podatke</em>.",
 "ar": "تبقى هذه البيانات على هاتفك. إزالة التطبيق أو مسح بيانات المتصفح يمحوها نهائياً. ويتوفر تصدير يدوي بصيغة JSON في <em>الإعدادات ← تصدير بياناتي</em>.",
 "tr": "Bu veriler telefonunuzda kalır. Uygulamayı kaldırmak ya da tarayıcı verilerini temizlemek onları kalıcı olarak siler. Elle JSON dışa aktarımı <em>Ayarlar → Verilerimi dışa aktar</em> altındadır.",
 "fa": "این داده‌ها روی گوشی شما می‌ماند. حذف برنامه یا پاک‌کردن داده‌های مرورگر آن‌ها را برای همیشه از بین می‌برد. برون‌بری دستی JSON در <em>تنظیمات ← برون‌بری داده‌های من</em> در دسترس است.",
 "ur": "یہ ڈیٹا آپ ہی کے فون پر رہتا ہے۔ ایپ ہٹانے یا براؤزر کا ڈیٹا صاف کرنے سے یہ ہمیشہ کے لیے مٹ جاتا ہے۔ دستی JSON برآمد <em>ترتیبات ← میرا ڈیٹا برآمد کریں</em> میں دستیاب ہے۔",
 "hi": "यह डेटा आपके फ़ोन पर ही रहता है। ऐप हटाने या ब्राउज़र का डेटा साफ़ करने पर यह हमेशा के लिए मिट जाता है। मैन्युअल JSON निर्यात <em>सेटिंग्स → मेरा डेटा निर्यात करें</em> में उपलब्ध है।",
 "bn": "এই তথ্য আপনার ফোনেই থাকে। অ্যাপ মুছে ফেললে বা ব্রাউজারের তথ্য পরিষ্কার করলে তা চিরতরে মুছে যায়। হাতে-করা JSON রপ্তানি <em>সেটিংস → আমার তথ্য রপ্তানি</em>-তে পাওয়া যায়।",
 "id": "Data ini tetap di ponsel Anda. Menghapus aplikasi atau membersihkan data peramban akan menghapusnya secara permanen. Ekspor JSON manual tersedia di <em>Pengaturan → Ekspor data saya</em>.",
 "ms": "Data ini kekal pada telefon anda. Menyahpasang aplikasi atau mengosongkan data pelayar akan memadamnya selama-lamanya. Eksport JSON secara manual ada di <em>Tetapan → Eksport data saya</em>.",
 "zh": "这些数据留在您的手机上。卸载应用或清除浏览器数据会将其永久删除。手动 JSON 导出位于<em>设置 → 导出我的数据</em>。",
 "ja": "これらのデータは端末内に留まります。アプリの削除やブラウザのデータ消去で完全に消えます。手動の JSON 書き出しは<em>設定 → データを書き出す</em>にあります。",
 "so": "Xogtan waxay ku hartaa taleefankaaga. Ka saarista barnaamijka ama nadiifinta xogta biraawsarku gebi ahaanba way tirtiraysaa. Dhoofinta gacanta ee JSON waxaad ka helaysaa <em>Habaynta ← Dhoofi xogtayda</em>.",
 "sw": "Data hii hubaki kwenye simu yako. Kuondoa programu au kufuta data ya kivinjari huifuta kabisa. Uhamishaji wa JSON kwa mkono upo katika <em>Mipangilio → Hamisha data yangu</em>.",
 "ha": "Waɗannan bayanan suna zama a wayarka. Cire manhajar ko share bayanan burauza yana goge su har abada. Fitar da JSON da hannu tana a <em>Saituna → Fitar da bayanaina</em>.",
},

"priv.geo.h": {
 "fr": "Géolocalisation", "en": "Location", "es": "Geolocalización",
 "ru": "Геолокация", "bs": "Lokacija", "ar": "تحديد الموقع",
 "tr": "Konum", "fa": "موقعیت مکانی", "ur": "مقامِ وقوع",
 "hi": "स्थान", "bn": "অবস্থান", "id": "Lokasi", "ms": "Lokasi",
 "zh": "定位", "ja": "位置情報", "so": "Goobta", "sw": "Mahali ulipo",
 "ha": "Wurin da kake",
},

"priv.geo.p1": {
 "fr": "Si vous l'autorisez, votre position sert uniquement à :",
 "en": "If you allow it, your location is used only to:",
 "es": "Si lo autoriza, su ubicación sirve únicamente para:",
 "ru": "Если вы разрешите, ваше местоположение используется только для того, чтобы:",
 "bs": "Ako dopustite, vaša lokacija služi isključivo da:",
 "ar": "إن أذنت بذلك، يُستعمل موقعك لغرضين فقط:",
 "tr": "İzin verirseniz konumunuz yalnızca şunlar için kullanılır:",
 "fa": "در صورت اجازه، موقعیت شما تنها برای این‌ها به کار می‌رود:",
 "ur": "اگر آپ اجازت دیں تو آپ کا مقام صرف اِن کے لیے استعمال ہوتا ہے:",
 "hi": "यदि आप अनुमति दें, तो आपका स्थान केवल इनके लिए काम आता है:",
 "bn": "আপনি অনুমতি দিলে আপনার অবস্থান কেবল এসবের জন্য ব্যবহৃত হয়:",
 "id": "Jika Anda mengizinkan, lokasi Anda hanya dipakai untuk:",
 "ms": "Jika anda benarkan, lokasi anda hanya digunakan untuk:",
 "zh": "若您允许，您的位置仅用于：",
 "ja": "許可した場合、位置情報は次の用途にのみ使われます：",
 "so": "Haddii aad ogolaato, goobtaadu waxay u adeegtaa kaliya:",
 "sw": "Ukikubali, mahali ulipo hutumika tu ili:",
 "ha": "Idan ka bayar da izini, wurin da kake yana amfani ne kawai don:",
},
"priv.geo.l1": {
 "fr": "Calculer les horaires de prière et la direction de la Qibla localement, sur votre appareil",
 "en": "Compute prayer times and the Qibla direction locally, on your device",
 "es": "Calcular los horarios de oración y la dirección de la Qibla localmente, en su dispositivo",
 "ru": "Рассчитать время молитв и направление кыблы локально, на вашем устройстве",
 "bs": "Izračuna namaska vremena i smjer kible lokalno, na vašem uređaju",
 "ar": "حساب مواقيت الصلاة واتجاه القبلة محلياً على جهازك",
 "tr": "Namaz vakitlerini ve kıble yönünü cihazınızda yerel olarak hesaplamak",
 "fa": "محاسبهٔ اوقات نماز و جهت قبله، به‌صورت محلی روی دستگاه شما",
 "ur": "نماز کے اوقات اور سمتِ قبلہ آپ ہی کے آلے پر مقامی طور پر نکالنا",
 "hi": "नमाज़ के समय और क़िबला की दिशा आपके ही उपकरण पर स्थानीय रूप से निकालना",
 "bn": "নামাজের সময় ও কিবলার দিক আপনার যন্ত্রেই স্থানীয়ভাবে নির্ণয় করা",
 "id": "Menghitung waktu salat dan arah kiblat secara lokal, di perangkat Anda",
 "ms": "Mengira waktu solat dan arah kiblat secara setempat, pada peranti anda",
 "zh": "在您的设备上本地计算礼拜时间与朝向",
 "ja": "礼拝時刻とキブラの方角を端末内で算出する",
 "so": "In lagu xisaabiyo waqtiyada salaadda iyo jihada qiblada qalabkaaga gudihiisa",
 "sw": "Kukokotoa nyakati za sala na mwelekeo wa Kibla ndani ya kifaa chako",
 "ha": "Ƙididdige lokutan sallah da alkibla a cikin na'urarka",
},

"priv.geo.p2": {
 "fr": "Vous pouvez refuser le GPS et saisir votre ville manuellement. La position n'est jamais partagée avec un tiers autre que ce service de géocodage.",
 "en": "You may refuse GPS and enter your city by hand. Your location is never shared with anyone other than that geocoding service.",
 "es": "Puede rechazar el GPS e introducir su ciudad manualmente. La ubicación nunca se comparte con un tercero distinto de ese servicio de geocodificación.",
 "ru": "Вы можете отказаться от GPS и ввести город вручную. Местоположение никогда не передаётся никому, кроме этого сервиса геокодирования.",
 "bs": "Možete odbiti GPS i grad unijeti ručno. Lokacija se nikada ne dijeli ni s kim osim s tim servisom za geokodiranje.",
 "ar": "يمكنك رفض تحديد الموقع وإدخال اسم مدينتك يدوياً. ولا يُشارَك الموقع مع أي طرف سوى خدمة الترميز الجغرافي هذه.",
 "tr": "GPS'i reddedip şehrinizi elle girebilirsiniz. Konum, bu coğrafi kodlama hizmeti dışında hiç kimseyle paylaşılmaz.",
 "fa": "می‌توانید GPS را نپذیرید و نام شهر را دستی وارد کنید. موقعیت هرگز با کسی جز همین سرویس مکان‌یابی به اشتراک گذاشته نمی‌شود.",
 "ur": "آپ GPS سے انکار کر کے اپنا شہر ہاتھ سے لکھ سکتے ہیں۔ مقام اِس جیوکوڈنگ سروس کے سوا کسی کے ساتھ کبھی شریک نہیں کیا جاتا۔",
 "hi": "आप GPS से इनकार कर के अपना शहर हाथ से लिख सकते हैं। स्थान इस जियोकोडिंग सेवा के अलावा किसी के साथ कभी साझा नहीं किया जाता।",
 "bn": "আপনি GPS প্রত্যাখ্যান করে হাতে শহরের নাম লিখতে পারেন। এই জিওকোডিং সেবা ছাড়া অবস্থান আর কারও সঙ্গে কখনো ভাগ করা হয় না।",
 "id": "Anda boleh menolak GPS dan mengetik nama kota sendiri. Lokasi tidak pernah dibagikan kepada pihak mana pun selain layanan geocoding tersebut.",
 "ms": "Anda boleh menolak GPS dan menaip nama bandar sendiri. Lokasi tidak pernah dikongsi dengan mana-mana pihak selain perkhidmatan geokod itu.",
 "zh": "您可以拒绝 GPS，手动输入城市名。除该地理编码服务外，位置绝不与任何第三方共享。",
 "ja": "GPS を断って都市名を手入力することもできます。位置情報がこのジオコーディングサービス以外に渡ることはありません。",
 "so": "Waad diidi kartaa GPS-ka oo magaca magaaladaada gacanta ku qori kartaa. Goobta marnaba lama wadaago cid kale oo aan ahayn adeeggaas.",
 "sw": "Unaweza kukataa GPS na kuandika jina la mji wako mwenyewe. Mahali ulipo hakushirikiwi kamwe na mtu yeyote isipokuwa huduma hiyo ya kutafuta mahali.",
 "ha": "Kana iya ƙin GPS ka rubuta sunan garinka da hannu. Ba a taɓa raba wurin da kake da wani ba, sai wannan sabis ɗin kawai.",
},
"priv.geo.l2": {
 "fr": "Retrouver le nom de votre ville via le service public OpenStreetMap (Nominatim), qui reçoit vos coordonnées pour cette seule requête",
 "en": "Look up your city name through the public OpenStreetMap (Nominatim) service, which receives your coordinates for that single request",
 "es": "Buscar el nombre de su ciudad mediante el servicio público OpenStreetMap (Nominatim), que recibe sus coordenadas solo para esa consulta",
 "ru": "Определить название вашего города через публичный сервис OpenStreetMap (Nominatim), который получает ваши координаты только для этого запроса",
 "bs": "Pronađe naziv vašeg grada putem javnog servisa OpenStreetMap (Nominatim), koji prima vaše koordinate samo za taj upit",
 "ar": "معرفة اسم مدينتك عبر الخدمة العامة OpenStreetMap (Nominatim)، التي تتلقى إحداثياتك لهذا الطلب وحده",
 "tr": "Şehrinizin adını, koordinatlarınızı yalnızca bu istek için alan kamuya açık OpenStreetMap (Nominatim) hizmetiyle bulmak",
 "fa": "یافتن نام شهر شما از راه سرویس عمومی OpenStreetMap (Nominatim) که مختصات شما را تنها برای همین درخواست دریافت می‌کند",
 "ur": "آپ کے شہر کا نام عوامی سروس OpenStreetMap (Nominatim) کے ذریعے معلوم کرنا، جو صرف اِسی درخواست کے لیے آپ کے نقاط وصول کرتی ہے",
 "hi": "आपके शहर का नाम सार्वजनिक सेवा OpenStreetMap (Nominatim) से पता करना, जो केवल इसी अनुरोध के लिए आपके निर्देशांक पाती है",
 "bn": "সর্বজনীন সেবা OpenStreetMap (Nominatim)-এর মাধ্যমে আপনার শহরের নাম বের করা, যা কেবল এই অনুরোধের জন্যই আপনার স্থানাঙ্ক পায়",
 "id": "Mencari nama kota Anda lewat layanan publik OpenStreetMap (Nominatim), yang menerima koordinat Anda hanya untuk permintaan itu",
 "ms": "Mencari nama bandar anda melalui perkhidmatan awam OpenStreetMap (Nominatim), yang menerima koordinat anda untuk permintaan itu sahaja",
 "zh": "通过公共服务 OpenStreetMap (Nominatim) 查询您所在城市的名称；它仅为该次请求接收您的坐标",
 "ja": "公共サービス OpenStreetMap (Nominatim) で都市名を調べる。座標が渡るのはこの一度の問い合わせのためだけです",
 "so": "In magaca magaaladaada laga helo adeegga guud ee OpenStreetMap (Nominatim), oo hela iskuxirayaashaada codsigaas kaliya",
 "sw": "Kutafuta jina la mji wako kupitia huduma ya umma ya OpenStreetMap (Nominatim), inayopokea viwianishi vyako kwa ombi hilo pekee",
 "ha": "Nemo sunan garinka ta hanyar sabis ɗin jama'a OpenStreetMap (Nominatim), wanda ke karɓar wurinka don wannan buƙata kaɗai",
},

"priv.ext.h": {
 "fr": "Services externes utilisés", "en": "External services used",
 "es": "Servicios externos utilizados", "ru": "Используемые внешние сервисы",
 "bs": "Korišteni vanjski servisi", "ar": "الخدمات الخارجية المستعملة",
 "tr": "Kullanılan dış hizmetler", "fa": "سرویس‌های بیرونی مورد استفاده",
 "ur": "استعمال ہونے والی بیرونی سروسز", "hi": "उपयोग की गई बाहरी सेवाएँ",
 "bn": "ব্যবহৃত বাহ্যিক সেবা", "id": "Layanan eksternal yang dipakai",
 "ms": "Perkhidmatan luar yang digunakan", "zh": "所用的外部服务",
 "ja": "利用している外部サービス", "so": "Adeegyada dibadda ee la isticmaalo",
 "sw": "Huduma za nje zinazotumika", "ha": "Sabis na waje da ake amfani da su",
},

"priv.contact.h": {
 "fr": "Contact", "en": "Contact", "es": "Contacto", "ru": "Контакты",
 "bs": "Kontakt", "ar": "التواصل", "tr": "İletişim", "fa": "تماس",
 "ur": "رابطہ", "hi": "संपर्क", "bn": "যোগাযোগ", "id": "Kontak",
 "ms": "Hubungi", "zh": "联系", "ja": "お問い合わせ", "so": "Xiriir",
 "sw": "Mawasiliano", "ha": "Tuntuɓa",
},
"priv.ext.l1": {
 "fr": "<strong>api.quran.com</strong> — fournit le texte du Coran et ses traductions. Aucune donnée personnelle n'y est envoyée.",
 "en": "<strong>api.quran.com</strong> — supplies the Qur'an text and its translations. No personal data is sent to it.",
 "es": "<strong>api.quran.com</strong> — proporciona el texto del Corán y sus traducciones. No se le envía ningún dato personal.",
 "ru": "<strong>api.quran.com</strong> — предоставляет текст Корана и его переводы. Личные данные туда не отправляются.",
 "bs": "<strong>api.quran.com</strong> — daje tekst Kur'ana i njegove prijevode. Nikakvi lični podaci se ne šalju.",
 "ar": "<strong>api.quran.com</strong> — يوفّر نص القرآن وترجماته. ولا تُرسَل إليه أي بيانات شخصية.",
 "tr": "<strong>api.quran.com</strong> — Kur'an metnini ve çevirilerini sağlar. Oraya hiçbir kişisel veri gönderilmez.",
 "fa": "<strong>api.quran.com</strong> — متن قرآن و ترجمه‌هایش را فراهم می‌کند. هیچ داده‌ای شخصی به آن فرستاده نمی‌شود.",
 "ur": "<strong>api.quran.com</strong> — قرآن کا متن اور اس کے تراجم فراہم کرتا ہے۔ اسے کوئی ذاتی معلومات نہیں بھیجی جاتی۔",
 "hi": "<strong>api.quran.com</strong> — क़ुरआन का पाठ और उसके अनुवाद देता है। इसे कोई निजी जानकारी नहीं भेजी जाती।",
 "bn": "<strong>api.quran.com</strong> — কুরআনের পাঠ ও তার অনুবাদ সরবরাহ করে। এতে কোনো ব্যক্তিগত তথ্য পাঠানো হয় না।",
 "id": "<strong>api.quran.com</strong> — menyediakan teks Al-Qur'an dan terjemahannya. Tidak ada data pribadi yang dikirim ke sana.",
 "ms": "<strong>api.quran.com</strong> — membekalkan teks al-Quran dan terjemahannya. Tiada data peribadi dihantar ke sana.",
 "zh": "<strong>api.quran.com</strong> —— 提供古兰经文本及其译文。不会向其发送任何个人数据。",
 "ja": "<strong>api.quran.com</strong> — クルアーンの本文と訳文を提供します。個人データは一切送信されません。",
 "so": "<strong>api.quran.com</strong> — waxay bixisaa qoraalka Quraanka iyo tarjumaadihiisa. Xog shakhsi ah looma diro.",
 "sw": "<strong>api.quran.com</strong> — hutoa matini ya Qur'ani na tafsiri zake. Hakuna data binafsi inayotumwa huko.",
 "ha": "<strong>api.quran.com</strong> — tana samar da rubutun Alqur'ani da fassarorinsa. Ba a aika mata wani bayanin sirri ba.",
},

"priv.ext.l2": {
 "fr": "<strong>nominatim.openstreetmap.org</strong> — géocodage de ville (recherche manuelle ou position GPS).",
 "en": "<strong>nominatim.openstreetmap.org</strong> — city geocoding (manual search or GPS position).",
 "es": "<strong>nominatim.openstreetmap.org</strong> — geocodificación de ciudad (búsqueda manual o posición GPS).",
 "ru": "<strong>nominatim.openstreetmap.org</strong> — геокодирование города (ручной поиск или положение GPS).",
 "bs": "<strong>nominatim.openstreetmap.org</strong> — geokodiranje grada (ručna pretraga ili GPS pozicija).",
 "ar": "<strong>nominatim.openstreetmap.org</strong> — ترميز جغرافي للمدينة (بحث يدوي أو موقع GPS).",
 "tr": "<strong>nominatim.openstreetmap.org</strong> — şehir coğrafi kodlaması (elle arama veya GPS konumu).",
 "fa": "<strong>nominatim.openstreetmap.org</strong> — مکان‌یابی شهر (جست‌وجوی دستی یا موقعیت GPS).",
 "ur": "<strong>nominatim.openstreetmap.org</strong> — شہر کی جیوکوڈنگ (دستی تلاش یا GPS مقام)۔",
 "hi": "<strong>nominatim.openstreetmap.org</strong> — शहर की जियोकोडिंग (हाथ से खोज या GPS स्थान)।",
 "bn": "<strong>nominatim.openstreetmap.org</strong> — শহরের জিওকোডিং (হাতে খোঁজা বা GPS অবস্থান)।",
 "id": "<strong>nominatim.openstreetmap.org</strong> — geocoding kota (pencarian manual atau posisi GPS).",
 "ms": "<strong>nominatim.openstreetmap.org</strong> — geokod bandar (carian manual atau kedudukan GPS).",
 "zh": "<strong>nominatim.openstreetmap.org</strong> —— 城市地理编码（手动搜索或 GPS 定位）。",
 "ja": "<strong>nominatim.openstreetmap.org</strong> — 都市のジオコーディング（手入力検索または GPS 位置）。",
 "so": "<strong>nominatim.openstreetmap.org</strong> — helitaanka magaalada (raadin gacan ah ama goobta GPS).",
 "sw": "<strong>nominatim.openstreetmap.org</strong> — kutafuta mji (utafutaji wa mkono au nafasi ya GPS).",
 "ha": "<strong>nominatim.openstreetmap.org</strong> — nemo gari (bincike da hannu ko wurin GPS).",
},

"priv.ext.l3": {
 "fr": "<strong>fonts.googleapis.com</strong> — police de caractères, chargée une fois puis mise en cache.",
 "en": "<strong>fonts.googleapis.com</strong> — typeface, loaded once then cached.",
 "es": "<strong>fonts.googleapis.com</strong> — tipografía, cargada una vez y luego almacenada en caché.",
 "ru": "<strong>fonts.googleapis.com</strong> — шрифт, загружается один раз и кэшируется.",
 "bs": "<strong>fonts.googleapis.com</strong> — font, učita se jednom pa se sprema u priručnu memoriju.",
 "ar": "<strong>fonts.googleapis.com</strong> — الخط، يُحمَّل مرة واحدة ثم يُخزَّن مؤقتاً.",
 "tr": "<strong>fonts.googleapis.com</strong> — yazı tipi; bir kez indirilir, sonra önbelleğe alınır.",
 "fa": "<strong>fonts.googleapis.com</strong> — قلم، یک‌بار بارگیری و سپس ذخیره می‌شود.",
 "ur": "<strong>fonts.googleapis.com</strong> — فونٹ، ایک بار لوڈ ہو کر محفوظ ہو جاتا ہے۔",
 "hi": "<strong>fonts.googleapis.com</strong> — फ़ॉन्ट, एक बार लोड होकर कैश हो जाता है।",
 "bn": "<strong>fonts.googleapis.com</strong> — ফন্ট, একবার লোড হয়ে ক্যাশে থাকে।",
 "id": "<strong>fonts.googleapis.com</strong> — huruf, dimuat sekali lalu disimpan di cache.",
 "ms": "<strong>fonts.googleapis.com</strong> — fon, dimuatkan sekali lalu disimpan dalam cache.",
 "zh": "<strong>fonts.googleapis.com</strong> —— 字体，加载一次后缓存。",
 "ja": "<strong>fonts.googleapis.com</strong> — フォント。一度読み込んだ後はキャッシュされます。",
 "so": "<strong>fonts.googleapis.com</strong> — farta qoraalka, mar keliya ayaa la soo dejiyaa oo la keydiyaa.",
 "sw": "<strong>fonts.googleapis.com</strong> — fonti, hupakiwa mara moja kisha huhifadhiwa.",
 "ha": "<strong>fonts.googleapis.com</strong> — rubutu, ana ɗauka sau ɗaya sannan a ajiye.",
},
"priv.ext.p": {
 "fr": "Ces requêtes réseau contiennent l'adresse IP de votre appareil, comme pour toute connexion Internet, mais aucune information identifiante n'est ajoutée par Sakina.",
 "en": "These network requests carry your device's IP address, as any Internet connection does, but Sakina adds no identifying information of its own.",
 "es": "Estas peticiones de red contienen la dirección IP de su dispositivo, como cualquier conexión a Internet, pero Sakina no añade ninguna información identificativa.",
 "ru": "Эти сетевые запросы содержат IP-адрес вашего устройства, как и любое интернет-соединение, но Sakina не добавляет к ним никаких опознавательных сведений.",
 "bs": "Ovi mrežni zahtjevi sadrže IP adresu vašeg uređaja, kao i svaka internetska veza, ali Sakina ne dodaje nikakve podatke po kojima biste se mogli prepoznati.",
 "ar": "تحمل هذه الطلبات عنوان IP لجهازك، كأي اتصال بالإنترنت، لكن Sakina لا يضيف إليها أي معلومة تعرّف بك.",
 "tr": "Bu ağ istekleri, her İnternet bağlantısında olduğu gibi cihazınızın IP adresini taşır; ancak Sakina bunlara kimliğinizi belirten hiçbir bilgi eklemez.",
 "fa": "این درخواست‌های شبکه نشانی IP دستگاه شما را در بر دارند، مانند هر اتصال اینترنتی دیگری؛ اما Sakina هیچ اطلاعات شناسایی‌کننده‌ای به آن‌ها نمی‌افزاید.",
 "ur": "اِن نیٹ ورک درخواستوں میں آپ کے آلے کا IP پتہ ہوتا ہے، جیسا کہ ہر انٹرنیٹ رابطے میں ہوتا ہے، مگر Sakina اِن میں کوئی شناختی معلومات نہیں جوڑتا۔",
 "hi": "इन नेटवर्क अनुरोधों में आपके उपकरण का IP पता होता है, जैसा हर इंटरनेट संपर्क में होता है, पर Sakina उनमें कोई पहचान वाली जानकारी नहीं जोड़ता।",
 "bn": "এই নেটওয়ার্ক অনুরোধে আপনার যন্ত্রের IP ঠিকানা থাকে, যেমন যেকোনো ইন্টারনেট সংযোগে থাকে; তবে Sakina এতে শনাক্তকারী কোনো তথ্য যোগ করে না।",
 "id": "Permintaan jaringan ini memuat alamat IP perangkat Anda, seperti pada setiap koneksi Internet, tetapi Sakina tidak menambahkan informasi pengenal apa pun.",
 "ms": "Permintaan rangkaian ini membawa alamat IP peranti anda, seperti mana-mana sambungan Internet, tetapi Sakina tidak menambah sebarang maklumat pengenalan.",
 "zh": "这些网络请求会带上您设备的 IP 地址，任何互联网连接都是如此；但 Sakina 不会额外附加任何可识别身份的信息。",
 "ja": "これらの通信には、インターネット接続である以上、端末の IP アドレスが含まれます。ただし Sakina が身元を示す情報を付け加えることはありません。",
 "so": "Codsiyadan shabakadeed waxay wataan cinwaanka IP ee qalabkaaga, sida xiriir kasta oo Internet ah, laakiin Sakina wax macluumaad lagu aqoonsado kuma darto.",
 "sw": "Maombi haya ya mtandao hubeba anwani ya IP ya kifaa chako, kama ilivyo kwa muunganisho wowote wa Intaneti, lakini Sakina haiongezi taarifa yoyote inayokutambulisha.",
 "ha": "Waɗannan buƙatun hanyar sadarwa suna ɗauke da adireshin IP na na'urarka, kamar kowace haɗin Intanet, amma Sakina ba ta ƙara wani bayanin da zai gane ka ba.",
},

"priv.contact.p": {
 "fr": "Pour toute question sur cette politique, contactez le développeur via la fiche de l'application sur le Google Play Store.",
 "en": "For any question about this policy, contact the developer through the app's page on the Google Play Store.",
 "es": "Para cualquier duda sobre esta política, contacte con el desarrollador a través de la ficha de la aplicación en Google Play Store.",
 "ru": "По любым вопросам об этой политике свяжитесь с разработчиком через страницу приложения в Google Play Store.",
 "bs": "Za sva pitanja o ovoj politici obratite se razvijatelju putem stranice aplikacije na Google Play Storeu.",
 "ar": "لأي سؤال عن هذه السياسة، تواصل مع المطوّر عبر صفحة التطبيق في متجر Google Play.",
 "tr": "Bu politikayla ilgili her soru için, uygulamanın Google Play Store sayfasından geliştiriciye ulaşın.",
 "fa": "برای هر پرسشی دربارهٔ این سیاست، از راه صفحهٔ برنامه در Google Play Store با توسعه‌دهنده تماس بگیرید.",
 "ur": "اِس پالیسی سے متعلق کسی بھی سوال کے لیے، Google Play Store پر ایپ کے صفحے سے ڈویلپر سے رابطہ کریں۔",
 "hi": "इस नीति से जुड़े किसी भी सवाल के लिए, Google Play Store पर ऐप के पृष्ठ से डेवलपर से संपर्क करें।",
 "bn": "এই নীতি সম্পর্কে যেকোনো প্রশ্নে, Google Play Store-এ অ্যাপের পাতা থেকে ডেভেলপারের সঙ্গে যোগাযোগ করুন।",
 "id": "Untuk pertanyaan apa pun tentang kebijakan ini, hubungi pengembang lewat halaman aplikasi di Google Play Store.",
 "ms": "Untuk sebarang pertanyaan tentang dasar ini, hubungi pembangun melalui halaman aplikasi di Google Play Store.",
 "zh": "如对本政策有任何疑问，请通过 Google Play 商店的应用页面联系开发者。",
 "ja": "本ポリシーに関するお問い合わせは、Google Play ストアのアプリページから開発者へご連絡ください。",
 "so": "Su'aal kasta oo ku saabsan siyaasaddan, kala xiriir horumariyaha bogga barnaamijka ee Google Play Store.",
 "sw": "Kwa swali lolote kuhusu sera hii, wasiliana na msanidi kupitia ukurasa wa programu kwenye Google Play Store.",
 "ha": "Don kowace tambaya game da wannan manufa, tuntuɓi mai haɓakawa ta shafin manhajar a Google Play Store.",
},
}
