#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Notes de source et invitations de recherche des livres.

Deux familles qui partaient brutes a l'ecran : la note qui dit d'ou vient le
livre, et le texte du champ de recherche — qui sert aussi de nom accessible
depuis que les placeholders portent une etiquette. Un lecteur japonais lisait
« Chercher un aliment (datte, miel, nigelle…) » au-dessus d'un livre traduit.

Les titres d'ouvrage et les noms d'auteur ne se traduisent pas : seul ce qui
les entoure change de langue.
"""

LOTS = {

"bkp.fruits": {
 "fr": "Chercher un aliment (datte, miel, nigelle…)",
 "en": "Search a food (date, honey, black seed…)",
 "es": "Buscar un alimento (dátil, miel, comino negro…)",
 "ru": "Искать продукт (финик, мёд, чёрный тмин…)",
 "bs": "Traži namirnicu (hurma, med, crni kim…)",
 "ar": "ابحث عن طعام (تمر، عسل، حبة سوداء…)",
 "tr": "Bir besin ara (hurma, bal, çörek otu…)",
 "fa": "جست‌وجوی خوراک (خرما، عسل، سیاه‌دانه…)",
 "ur": "غذا تلاش کریں (کھجور، شہد، کلونجی…)",
 "hi": "आहार खोजें (खजूर, शहद, कलौंजी…)",
 "bn": "খাদ্য খুঁজুন (খেজুর, মধু, কালোজিরা…)",
 "id": "Cari makanan (kurma, madu, habbatussauda…)",
 "ms": "Cari makanan (kurma, madu, habbatussauda…)",
 "zh": "搜索食物（椰枣、蜂蜜、黑种草…）",
 "ja": "食物を検索（ナツメヤシ、蜂蜜、ブラックシード…）",
 "so": "Raadi cunto (timir, malab, habbatu sawda…)",
 "sw": "Tafuta chakula (tende, asali, habbat sauda…)",
 "ha": "Nemi abinci (dabino, zuma, habbatus sauda…)",
},

"bkp.miracles": {
 "fr": "Chercher un chapitre (défi, Rome, comptages…)",
 "en": "Search a chapter (challenge, Rome, counts…)",
 "es": "Buscar un capítulo (desafío, Roma, recuentos…)",
 "ru": "Искать главу (вызов, Рим, подсчёты…)",
 "bs": "Traži poglavlje (izazov, Rim, brojanja…)",
 "ar": "ابحث عن فصل (التحدي، الروم، الإحصاءات…)",
 "tr": "Bir bölüm ara (meydan okuma, Rûm, sayımlar…)",
 "fa": "جست‌وجوی فصل (تحدی، روم، شمارش‌ها…)",
 "ur": "باب تلاش کریں (چیلنج، روم، شماریات…)",
 "hi": "अध्याय खोजें (चुनौती, रोम, गणनाएँ…)",
 "bn": "অধ্যায় খুঁজুন (চ্যালেঞ্জ, রোম, গণনা…)",
 "id": "Cari bab (tantangan, Romawi, perhitungan…)",
 "ms": "Cari bab (cabaran, Rom, pengiraan…)",
 "zh": "搜索章节（挑战、罗马、计数…）",
 "ja": "章を検索（挑戦、ローマ、計数…）",
 "so": "Raadi cutub (caqabad, Ruum, tirinta…)",
 "sw": "Tafuta sura (changamoto, Rumi, mahesabu…)",
 "ha": "Nemi babi (ƙalubale, Rum, ƙirge…)",
},

"bkn.riyad.1": {
 "fr": "Texte intégral, reproduit tel quel — édition riyad.fr.tc",
 "en": "Full text, reproduced as is — riyad.fr.tc edition",
 "es": "Texto íntegro, reproducido tal cual — edición riyad.fr.tc",
 "ru": "Полный текст, воспроизведён без изменений — издание riyad.fr.tc",
 "bs": "Cjelovit tekst, prenesen doslovno — izdanje riyad.fr.tc",
 "ar": "النص الكامل، منقول كما هو — طبعة riyad.fr.tc",
 "tr": "Tam metin, olduğu gibi aktarıldı — riyad.fr.tc baskısı",
 "fa": "متن کامل، بی‌کم‌وکاست — نسخهٔ riyad.fr.tc",
 "ur": "مکمل متن، جوں کا توں — riyad.fr.tc ایڈیشن",
 "hi": "पूर्ण पाठ, यथावत — riyad.fr.tc संस्करण",
 "bn": "পূর্ণ পাঠ, হুবহু — riyad.fr.tc সংস্করণ",
 "id": "Teks lengkap, disalin apa adanya — edisi riyad.fr.tc",
 "ms": "Teks penuh, disalin seadanya — edisi riyad.fr.tc",
 "zh": "全文照录 —— riyad.fr.tc 版",
 "ja": "全文をそのまま収録 — riyad.fr.tc 版",
 "so": "Qoraal buuxa, sidiisii loo soo guuriyey — daabacaadda riyad.fr.tc",
 "sw": "Maandishi kamili, kama yalivyo — toleo la riyad.fr.tc",
 "ha": "Cikakken rubutu, kamar yadda yake — bugun riyad.fr.tc",
},

"bkn.citadelle.1": {
 "fr": "Texte intégral — Hisn al-Muslim, Sa'îd Ibn 'Alî Ibn Wahf Al-Qahtânî",
 "en": "Full text — Hisn al-Muslim, Sa'id Ibn 'Ali Ibn Wahf al-Qahtani",
 "es": "Texto íntegro — Hisn al-Muslim, Sa'id Ibn 'Ali Ibn Wahf al-Qahtani",
 "ru": "Полный текст — Хисн аль-Муслим, Саид ибн Али ибн Вахф аль-Кахтани",
 "bs": "Cjelovit tekst — Hisn al-Muslim, Sa'id ibn Ali ibn Wahf el-Kahtani",
 "ar": "النص الكامل — حصن المسلم، سعيد بن علي بن وهف القحطاني",
 "tr": "Tam metin — Hisnü'l-Müslim, Sa'îd b. Alî b. Vehf el-Kahtânî",
 "fa": "متن کامل — حصن المسلم، سعید بن علی بن وهف قحطانی",
 "ur": "مکمل متن — حصن المسلم، سعید بن علی بن وہف القحطانی",
 "hi": "पूर्ण पाठ — हिस्न अल-मुस्लिम, सईद बिन अली बिन वहफ़ अल-क़हतानी",
 "bn": "পূর্ণ পাঠ — হিসনুল মুসলিম, সাঈদ ইবনে আলী ইবনে ওয়াহফ আল-কাহতানী",
 "id": "Teks lengkap — Hisnul Muslim, Sa'id bin Ali bin Wahf al-Qahthani",
 "ms": "Teks penuh — Hisnul Muslim, Sa'id bin Ali bin Wahf al-Qahtani",
 "zh": "全文 ——《穆斯林的堡垒》，赛义德·本·阿里·本·瓦赫夫·卡赫塔尼",
 "ja": "全文 — ヒスヌル・ムスリム、サイード・イブン・アリー・イブン・ワフフ・アル＝カフターニー",
 "so": "Qoraal buuxa — Xisnul Muslim, Saciid bin Cali bin Wahf al-Qahtaani",
 "sw": "Maandishi kamili — Hisnul Muslim, Said bin Ali bin Wahf al-Qahtani",
 "ha": "Cikakken rubutu — Hisnul Muslim, Sa'id bin Ali bin Wahf al-Qahtani",
},

"bkn.asma.1": {
 "fr": "D'après la tradition classique — références coraniques et prophétiques",
 "en": "From the classical tradition — Qur'anic and prophetic references",
 "es": "Según la tradición clásica — referencias coránicas y proféticas",
 "ru": "По классической традиции — коранические и пророческие ссылки",
 "bs": "Prema klasičnoj predaji — kur'anski i vjerovjesnički izvori",
 "ar": "وفق التراث الكلاسيكي — مراجع قرآنية ونبوية",
 "tr": "Klasik gelenek uyarınca — Kur'ânî ve nebevî kaynaklar",
 "fa": "بر پایهٔ سنت کلاسیک — ارجاعات قرآنی و نبوی",
 "ur": "کلاسیکی روایت کے مطابق — قرآنی و نبوی حوالہ جات",
 "hi": "शास्त्रीय परंपरा के अनुसार — क़ुरआनी और नबवी संदर्भ",
 "bn": "ধ্রুপদী ঐতিহ্য অনুসারে — কুরআনি ও নববি সূত্র",
 "id": "Menurut tradisi klasik — rujukan Qur'ani dan nabawi",
 "ms": "Menurut tradisi klasik — rujukan Qurani dan nabawi",
 "zh": "依古典传统 —— 古兰与圣训出处",
 "ja": "古典的伝承に基づく — クルアーンとスンナの典拠",
 "so": "Sida caadada qadiimka ah — tixraacyo Quraan iyo Sunno",
 "sw": "Kwa mujibu wa mapokeo ya kale — marejeo ya Qur'ani na Sunna",
 "ha": "Bisa al'adar gargajiya — nassoshin Alƙur'ani da Sunna",
},

"bkn.asma.2": {
 "fr": "Invocation &amp; introspection de chaque nom : « Les Essentiels — Les 99 Noms d'Allah » de Souad El Mansouri, éditions Al Bouraq",
 "en": "Supplication &amp; reflection for each name: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "es": "Súplica y reflexión de cada nombre: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "ru": "Мольба и размышление к каждому имени: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "bs": "Dova i promišljanje uz svako ime: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "ar": "دعاء وتأمل لكل اسم: « Les Essentiels — Les 99 Noms d'Allah »، سعاد المنصوري، دار البراق",
 "tr": "Her isim için dua ve tefekkür: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "fa": "دعا و تأمل برای هر نام: « Les Essentiels — Les 99 Noms d'Allah »، سعاد المنصوری، البراق",
 "ur": "ہر نام کے لیے دعا و تدبر: « Les Essentiels — Les 99 Noms d'Allah »، سعاد المنصوری، البراق",
 "hi": "प्रत्येक नाम के लिए दुआ और चिंतन: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "bn": "প্রতিটি নামের দোয়া ও অনুধ্যান: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "id": "Doa &amp; perenungan tiap nama: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "ms": "Doa &amp; renungan bagi setiap nama: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "zh": "各尊名的祈祷与省思：« Les Essentiels — Les 99 Noms d'Allah »，Souad El Mansouri，Al Bouraq",
 "ja": "各御名のドゥアーと内省：« Les Essentiels — Les 99 Noms d'Allah »、Souad El Mansouri、Al Bouraq",
 "so": "Duco iyo milicsi magac kasta: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "sw": "Dua na tafakuri kwa kila jina: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
 "ha": "Addu'a da tunani ga kowane suna: « Les Essentiels — Les 99 Noms d'Allah », Souad El Mansouri, Al Bouraq",
},

"bkn.fruits.1": {
 "fr": "Versets et hadiths cités intégralement ; recherche et rédaction originales — sources en fin de lecture",
 "en": "Verses and hadiths quoted in full; original research and writing — sources at the end",
 "es": "Versículos y hadices citados íntegramente; investigación y redacción originales — fuentes al final",
 "ru": "Аяты и хадисы приведены полностью; собственное исследование и текст — источники в конце",
 "bs": "Ajeti i hadisi navedeni u cijelosti; vlastito istraživanje i tekst — izvori na kraju",
 "ar": "الآيات والأحاديث منقولة كاملة؛ بحث وصياغة أصليان — المصادر في الآخر",
 "tr": "Ayet ve hadisler tam olarak alıntılandı; özgün araştırma ve yazım — kaynaklar sonda",
 "fa": "آیات و احادیث به‌طور کامل نقل شده؛ پژوهش و نگارش اصیل — منابع در پایان",
 "ur": "آیات و احادیث مکمل نقل؛ اصل تحقیق و تحریر — مآخذ آخر میں",
 "hi": "आयतें और हदीसें पूर्ण उद्धृत; मौलिक शोध और लेखन — स्रोत अंत में",
 "bn": "আয়াত ও হাদিস পূর্ণ উদ্ধৃত; মৌলিক গবেষণা ও রচনা — সূত্র শেষে",
 "id": "Ayat dan hadis dikutip lengkap; riset dan penulisan orisinal — sumber di akhir",
 "ms": "Ayat dan hadis dipetik sepenuhnya; penyelidikan dan penulisan asli — sumber di akhir",
 "zh": "经文与圣训全文引用；原创研究与撰写 —— 出处见文末",
 "ja": "章句とハディースは全文引用。研究と執筆は独自 — 出典は巻末",
 "so": "Aayadaha iyo xadiisyada oo dhammaystiran; cilmi-baaris iyo qoraal asal ah — ilaha dhamaadka",
 "sw": "Aya na hadithi zimenukuliwa kikamilifu; utafiti na uandishi asilia — vyanzo mwishoni",
 "ha": "An kawo ayoyi da hadisai cikakke; bincike da rubutu na asali — tushe a ƙarshe",
},

"bkn.miracles.1": {
 "fr": "Versets et hadiths cités intégralement ; comptages refaits sur les 6236 versets, dans les deux orthographes — sources et méthode en fin de lecture",
 "en": "Verses and hadiths quoted in full; counts redone over all 6236 verses, in both orthographies — sources and method at the end",
 "es": "Versículos y hadices citados íntegramente; recuentos rehechos sobre los 6236 versículos, en ambas ortografías — fuentes y método al final",
 "ru": "Аяты и хадисы приведены полностью; подсчёты выполнены заново по всем 6236 аятам, в обеих орфографиях — источники и метод в конце",
 "bs": "Ajeti i hadisi navedeni u cijelosti; brojanja ponovljena na svih 6236 ajeta, u oba pravopisa — izvori i metoda na kraju",
 "ar": "الآيات والأحاديث منقولة كاملة؛ أُعيدت الإحصاءات على الآيات الـ6236 كلها، بالرسمين — المصادر والمنهج في الآخر",
 "tr": "Ayet ve hadisler tam olarak alıntılandı; sayımlar 6236 ayetin tamamı üzerinde, iki imlâ ile yeniden yapıldı — kaynaklar ve yöntem sonda",
 "fa": "آیات و احادیث به‌طور کامل نقل شده؛ شمارش‌ها روی هر ۶۲۳۶ آیه و در هر دو رسم‌الخط بازانجام شده — منابع و روش در پایان",
 "ur": "آیات و احادیث مکمل نقل؛ شماریات تمام 6236 آیات پر، دونوں املاؤں میں دوبارہ — مآخذ و طریقہ آخر میں",
 "hi": "आयतें और हदीसें पूर्ण उद्धृत; गणनाएँ सभी 6236 आयतों पर, दोनों वर्तनियों में पुनः — स्रोत और विधि अंत में",
 "bn": "আয়াত ও হাদিস পূর্ণ উদ্ধৃত; গণনা সমস্ত ৬২৩৬ আয়াতে, দুই বানানেই পুনরায় — সূত্র ও পদ্ধতি শেষে",
 "id": "Ayat dan hadis dikutip lengkap; perhitungan diulang atas seluruh 6236 ayat, dalam dua ejaan — sumber dan metode di akhir",
 "ms": "Ayat dan hadis dipetik sepenuhnya; pengiraan diulang ke atas kesemua 6236 ayat, dalam dua ejaan — sumber dan kaedah di akhir",
 "zh": "经文与圣训全文引用；计数在全部 6236 节上、按两种正字法重做 —— 出处与方法见文末",
 "ja": "章句とハディースは全文引用。計数は全6236節を対象に、二つの正書法で取り直し — 出典と方法は巻末",
 "so": "Aayadaha iyo xadiisyada oo dhammaystiran; tirinta dib loogu sameeyey 6236 aayadood oo dhan, labada higgaad — ilaha iyo habka dhamaadka",
 "sw": "Aya na hadithi zimenukuliwa kikamilifu; mahesabu yamerudiwa kwa aya zote 6236, kwa hijai zote mbili — vyanzo na mbinu mwishoni",
 "ha": "An kawo ayoyi da hadisai cikakke; an sake ƙirge dukkan ayoyi 6236, a rubuce-rubuce biyu — tushe da hanya a ƙarshe",
},
}
